name-template: 'Biblia-Arabica.com Bibliography data version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH-dev' # Different config files are referenced by workflows in different branches to allow 'dev' to be prepended only to development releases. See input: config-name in workflow file.
categories:
  - title: '📚 New Content'
    labels:
      - 'changelog: new content'
  - title: '📝 Corrected Content'
    labels:
      - 'changelog: corrected content'
  - title: '📐 Changes to Schema, Standards, or Data Model'
    labels:
      - 'changelog: schema changes'
  - title: '💡 Metadata or App Enhancements'
    labels:
      - 'changelog: metadata/app enhancements'
  - title: '🐛 Metadata and Application Fixes'
    labels:
      - 'changelog: metadata/app fixes'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
prerelease: true # This can also be specified in the workflow file to allow differences between branches
version-resolver:
  major:
    labels:
      - 'changelog: major release'
  minor:
    labels:
      - 'changelog: schema changes'
      - 'changelog: new content'
      - 'changelog: metadata/app enhancements'
  patch:
    labels:
      - 'changelog: metadata/app fixes'
      - 'changelog: corrected content'
  default: patch
exclude-labels:
  - 'changelog: ignore'
template: |
  This release is intended for testing data to be released on the [Biblia-Arabica.com Bibliography](https://biblia-arabica.com/bibl) website.
  
  The .xar package is intended to be used in [eXist-db 6.x](http://exist-db.org/exist/apps/homepage/index.html) with the [Srophé app Biblia-Arabica fork](https://github.com/biblia-arabica/srophe-eXist-app).
  
  You can also make your own .xar of the data by downloading this repo and running ant in the repo directory. A docker image of eXist-db with this package pre-installed is available at https://github.com/orgs/biblia-arabica/packages.
  
  ## Changes
  
  $CHANGES
  
  ## Contributors
  
  $CONTRIBUTORS
